[k3s_master]
k3s01 ansible_host=192.168.1.70

[k3s_nodes]
k3s02 ansible_host=192.168.1.71
k3s03 ansible_host=192.168.1.72

[k3s:children]
k3s_master
k3s_nodes

[k3s:vars]
ansible_user=root
ansible_password=changeme
ansible_python_interpreter=/usr/bin/python3
